<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>RPCForSMBLibrary</AssemblyName>
    <NoWarn>1573;1591</NoWarn>
    <RootNamespace>SMBLibrary</RootNamespace>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Authors>Vincent LE TOUX;DryvIQ</Authors>
    <PackageDescription>RPCForSMBLibrary is an open-source C# SMB 1.0/CIFS, SMB 2.0, SMB 2.1 and SMB 3.0 server and client implementation</PackageDescription>
    <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/vletoux/RPCForSMBLibrary</PackageProjectUrl>
    <RepositoryUrl>https://github.com/portalarchitects/RPCForSMBLibrary</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SMBLibrary" Version="1.5.3.4" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="all" />
    <PackageReference Include="MinVer" Version="6.0.0" PrivateAssets="all" />
  </ItemGroup>

</Project>
